# -*- coding: utf-8 -*-
"""
Created on Wed Nov  5 10:08:12 2025

@author: emanu
"""

import os
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.dates import DateFormatter
#import seaborn as sns
import pandas as pd
import numpy as np
from datetime import date, timedelta
from datetime import datetime as dt
from dateutil.relativedelta import relativedelta
# Handle date time conversions between pandas and matplotlib
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
from scipy.signal import butter, filtfilt

from gradient_hist_min_max import process_dts_file_grad, df_time_calc_grad, extract_date_across_years_grad
from gradient_hist_min_max import alarm_plot_min_max_grad, remove_years_grad, stats_min_max_std_dates_grad

from temp_hist_min_max import df_time_calc_temp, extract_date_across_years_temp, remove_years_temp
from temp_hist_min_max import stats_min_max_std_dates_temp,alarm_plot_min_max_temp

from temp_diff_hist_min_max import df_time_calc_tempdiff, extract_date_across_years_tempdiff, eday_minus_week_tempdiff
from temp_diff_hist_min_max import remove_years_tempdiff, stats_min_max_std_tempdiff, stats_min_max_std_dates_tempdiff, alarm_plot_min_max_tempdiff

from data_creation import data_creation
from data_updating import data_updating
from data_jitter_correction import data_jitter_correction

import requests
from io import BytesIO
import base64
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage






from dash import Dash, dcc, html, Output, Input, State

plt.style.use('seaborn-v0_8-white')

# ------------------- Email Configuration -------------------
SMTP_SERVER = "smtp.gmail.com"         
SMTP_PORT = 587
EMAIL_SENDER = "geophysicsunb@gmail.com"   
EMAIL_PASSWORD = "qmyzqduwojfbwjen"   
EMAIL_RECIPIENT = "emanuel.degante@unb.ca " 
minutes=int(5)


def send_email_with_plots(

        img_bytes_temp,
        img_bytes_tempdiff,
        img_bytes_grad,
        
        anomaly_grad,
        anomaly_temp,
        anomaly_tempdiff,
        
        temp_day,

        
        current_time=None):
    
    if current_time is None:
        current_time = dt.now().replace(second=0, microsecond=0)

    """Send email with 3 inline plots."""

    # =========================================
    # Subject
    # =========================================

    if temp_day.size == 0:
    
        subject = ("No data available for the day")
    
    else:
    
        if anomaly_temp == "Y" and anomaly_tempdiff == "Y":
    
            subject = (
                "ALERT - Historical Norm Exceeded "
                "DTS Mactaquac Monitoring System"
            )
    
        else:
    
            subject = (
                "Normal Conditions: "
                "DTS Mactaquac Monitoring System"
            )
    # =========================================
    # Create message
    # =========================================

    msg = MIMEMultipart()

    msg["From"] = EMAIL_SENDER

    msg["To"] = EMAIL_RECIPIENT

    msg["Subject"] = subject

    # =========================================
    # HTML Body
    # =========================================

    body = f"""
    <html>

    <body>

        <p>AAR Team,</p>

        <p>
        This automated analysis was generated by DTScope using historical 
        DTS data from the fibre optic cable located at the SEPI-3 borehole
        <b></b>.
        </p>

        <p>
        <b>Time:</b> {current_time}
        </p>

        <hr>

        <h2>Temperature  </h2>

        <img src="cid:plot_temp"
             style="width:100%;  height:auto;">

        <br><br>

        <h2>Temperature Change</h2>

        <img src="cid:plot_tempdiff"
             style="width:100%;  height:auto;">

        <br><br>

        <h2>Temperature Gradient</h2>

        <img src="cid:plot_grad"
             style="width:100%;  height:auto;">

        <br><br>

        <hr>

        <p>
        Best regards,<br>
        DTScope Analytics
        </p>

    </body>

    </html>
    """

    # =========================================
    # Attach HTML
    # =========================================

    msg.attach(

        MIMEText(
            body,
            "html"
        )
    )

    # =========================================
    # Attach Images
    # =========================================

    images = [

        (
            img_bytes_temp,
            "plot_temp",
            "temperature.png"
        ),

        (
            img_bytes_tempdiff,
            "plot_tempdiff",
            "temperature_difference.png"
        ),

        (
            img_bytes_grad,
            "plot_grad",
            "gradient.png"
        )
    ]

    for img_bytes, cid, filename in images:

        img = MIMEImage(

            img_bytes,

            name=filename
        )

        img.add_header(

            "Content-ID",

            f"<{cid}>"
        )

        img.add_header(

            "Content-Disposition",

            "inline",

            filename=filename
        )

        msg.attach(img)

    # =========================================
    # Send Email
    # =========================================

    try:

        with smtplib.SMTP(
                SMTP_SERVER,
                SMTP_PORT) as server:

            server.starttls()

            server.login(
                EMAIL_SENDER,
                EMAIL_PASSWORD
            )

            server.send_message(msg)

        print(
            f"✅ Email sent successfully: "
            f"{subject}"
        )

    except Exception as e:

        print(
            f"❌ Error sending email: {e}"
        )


simulated_date = dt(2026, 1, 31)
def get_next_simulated_day():

    global simulated_date
    current_date = simulated_date
    simulated_date += timedelta(days=1)
    return current_date

    # Restart when reaching after 2023-12-30
    if simulated_date > dt(2026, 4, 29):
        simulated_date = dt(2026, 1, 30)

def create_figure():


    #year=(2023)     One day
    #month=(7)
    #day=(11)
    
   #dt_now= dt(year, month, day).strftime("%Y-%m-%d")   ====> when reading real data
    
    #dt_now=dt.now()
    #year=(dt.now().year)
    #month=(dt.now().month)
    #day=(dt.now().day)
    
    now = get_next_simulated_day()

    year = now.year
    month =now.month
    day = now.day
    
    year_db=str(year)
    month_db=str(month)
    month_db = simulated_date.strftime("%b").lower()
    
    j_n=3  
    
    day_diff=(2)
             # Elevation from top to bottom (Skiping "ele" amount of nodes)
    years_removed=[2014,2015, 2016, 2017, 2026]
    
    separate_figures=False
    
    nodes_from_bottom=10
    win=20
    #======================================Data Creation
    
    dataframe = pd.read_csv("F:\\0_Mactaquac_Data_Bases\\DTS_daily_Total.csv")
    
    df_daily, df_hourly, df_raw = data_creation(year_db,month_db)
    
    
    #======================================Updating Dataframe
    df_updated = data_updating(year_db, month_db)
    
    dataframe_2 = pd.read_csv("F:\\0_Mactaquac_Data_Bases\\DTS_daily_Total.csv")
    
    #====================================== Data Jitter Correction
    
    df_final=data_jitter_correction(dataframe_2, nodes_from_bottom, win)
    
    
    df_source =      pd.read_csv("F:\\0_Mactaquac_Data_Bases\\DTS_daily_Total_Jitter.csv")
    df_source_diff = pd.read_csv("F:\\0_Mactaquac_Data_Bases\\DTS_daily_Total_Jitter.csv")
    df_source_grad = pd.read_csv("F:\\0_Mactaquac_Data_Bases\\DTS_daily_Total_Jitter.csv")
    
    #================== Gradient_hist_min_max
    df_gradient, medians =process_dts_file_grad(df_source_grad)
    
    r,df_gradient_2, temp_day, d_1= df_time_calc_grad(year,month,day,df_gradient)
    
    same_day     = extract_date_across_years_grad(df_gradient_2, month, day)
    same_day     = remove_years_grad(same_day,     years_removed)
    
    Min_D, Min_Year, Max_D, Max_Year, Mean  =  stats_min_max_std_dates_grad(same_day)
    
    fig_grad, img_bytes_grad, img_base64_grad, anomaly_grad =alarm_plot_min_max_grad(r,temp_day,d_1, Min_D, Min_Year, Max_D, Max_Year, Mean, j_n, separate_figures)
    
    #================== Temp_hist_min_max
    
    r,df_temp, temp_day, d_1= df_time_calc_temp(year,month,day,df_source)
    
    same_day = extract_date_across_years_temp(df_temp, month, day)
    same_day     = remove_years_temp(same_day,     years_removed)
    
    Min_D, Min_Year, Max_D, Max_Year, Mean  =  stats_min_max_std_dates_temp(same_day)
    
    fig_temp, img_bytes_temp, img_base64_temp, anomaly_temp =alarm_plot_min_max_temp(r,temp_day,d_1,  Min_D, Min_Year, Max_D, Max_Year, Mean, j_n, separate_figures)
    
    
  
    #================== Temp_diff_hist_min_max
 
    df_source_diff_2 ,r,d_1,d_7, d_1_t, d_7_s=df_time_calc_tempdiff(year,month,day,day_diff, df_source_diff)
    
    same_day = extract_date_across_years_tempdiff(df_source_diff_2, month, day)
    same_day_m_7 = eday_minus_week_tempdiff(df_source_diff_2, d_7)
    
    df_1=same_day
    df_2=same_day_m_7
    
    same_day     = remove_years_tempdiff(same_day,     years_removed)
    same_day_m_7 = remove_years_tempdiff(same_day_m_7, years_removed)
    
    #same_day_dates=same_day
    
    time=same_day.index
    same_day=same_day.reset_index(drop=True)
    same_day_m_7=same_day_m_7.reset_index(drop=True)
    
    diff_7= same_day-same_day_m_7
    
    df_final_diff_7, Mean_diff_7, STD_diff_7  =  stats_min_max_std_tempdiff(diff_7)
    
    time_pd=pd.DataFrame(time)
    diff_7_df=diff_7.copy()
    diff_7_df.index = pd.to_datetime(time_pd.iloc[:,0])
    
    Min_D, Min_Year, Max_D, Max_Year, Mean  =  stats_min_max_std_dates_tempdiff(diff_7_df)
    
    
    temp_7= df_1.loc[d_1_t] - df_2.loc[d_7]
    
    fig_tempdiff, img_bytes_tempdiff, img_base64_tempdiff, anomaly_tempdiff =alarm_plot_min_max_tempdiff(r,temp_7,d_1, Min_D, Min_Year, Max_D, Max_Year, Mean, j_n, day_diff, d_7_s, separate_figures)
    

    
    return (fig_temp, img_bytes_temp, img_base64_temp, anomaly_temp, temp_day, 
            fig_tempdiff, img_bytes_tempdiff, img_base64_tempdiff, anomaly_tempdiff, 
            fig_grad, img_bytes_grad, img_base64_grad, anomaly_grad)

# ------------------- Dash App -------------------
app = Dash(__name__)



# ============================================
# Shared plot style
# ============================================

plot_style = {

    "width": "100%",

    "maxWidth": "1600px",

    "display": "block",

    "margin": "auto",

    "border": "1px solid lightgray",

    "padding": "10px",

    "backgroundColor": "white"
}


# ============================================
# Layout
# ============================================

app.layout = html.Div([

    # ========================================
    # Title
    # ========================================

    html.H1(

        "ThermaLert Real Time",

        style={
            'textAlign': 'center',
            'marginBottom': '30px'
        }
    ),

    # ========================================
    # Historical Temperature
    # ========================================

    html.Div([

        html.H3(
            "Temperature",
            style={'textAlign': 'center', 'fontSize': '30px'}
        ),

        html.Img(
            id="plot-1",
            style=plot_style
        )

    ]),

    html.Br(),

    # ========================================
    # Temperature Change
    # ========================================

    html.Div([

        html.H3(
            "Temperature Change",
            style={'textAlign': 'center', 'fontSize': '30px'}
        ),

        html.Img(
            id="plot-2",
            style=plot_style
        )

    ]),

    html.Br(),

    # ========================================
    # Temperature Gradient
    # ========================================

    html.Div([

        html.H3(
            "Temperature Gradient",
            style={'textAlign': 'center', 'fontSize': '30px'}
        ),

        html.Img(
            id="plot-3",
            style=plot_style
        )

    ]),

    # ========================================
    # Auto refresh
    # ========================================

    dcc.Interval(

        id="interval-refresh",

        interval=minutes * 60 * 1000,   # X minutes in milliseconds

        n_intervals=0
    ),

    # ========================================
    # First trigger storage
    # ========================================

    dcc.Store(

        id="first-trigger",

        data=True
    )

],
style={

    "backgroundColor": "#f5f5f5",

    "padding": "20px"
})


# ============================================
# Callback
# ============================================

@app.callback(

    Output("plot-1", "src"),
    Output("plot-2", "src"),
    Output("plot-3", "src"),
    Output("interval-refresh", "interval"),
    Output("first-trigger", "data"),

    Input("interval-refresh", "n_intervals"),

    State("first-trigger", "data")
)

def update_plot(n_intervals, first_trigger):

    (
        fig_temp,
        img_bytes_temp,
        img_base64_temp,
        anomaly_temp,
        temp_day,

        fig_tempdiff,
        img_bytes_tempdiff,
        img_base64_tempdiff,
        anomaly_tempdiff,
     
        fig_grad,
        img_bytes_grad,
        img_base64_grad,
        anomaly_grad

    ) = create_figure()

    # ==========================
    # Convert for Dash
    # ==========================

    img_src_temp = (
        "data:image/png;base64,"
        + img_base64_temp
    )

    img_src_tempdiff = (
        "data:image/png;base64,"
        + img_base64_tempdiff
    )
    
    img_src_grad = (
        "data:image/png;base64,"
        + img_base64_grad
    )

    # ==========================
    # Send Email
    # ==========================

    send_email_with_plots(
        img_bytes_temp,
        img_bytes_tempdiff,
        img_bytes_grad,
        anomaly_grad,
        anomaly_temp,
        anomaly_tempdiff,
        temp_day
        #current_time
    )

    # ==========================
    # Dashboard refresh
    # ==========================

    new_interval = minutes* 60 * 1000

    first_trigger = False

    return (
        img_src_temp,
        img_src_tempdiff,
        img_src_grad,
        new_interval,
        first_trigger,
    )

if __name__ == '__main__':
    app.run(
        debug=True,
        use_reloader=False,
        host="127.0.0.1",
        port=8050
    )
#http://127.0.0.1:8050/
